import api from './axiosConfig';
export const getMyProfile = () => api.get('/api/users/me');
export const updateMyProfile = (data) => api.put('/api/users/me', data);
export const getUserProfile = (username) => api.get(`/api/users/${username}`);
export const toggleFollow = (username) => api.post(`/api/users/${username}/follow`);
export const searchUsers = (query) => api.get(`/api/users/search?query=${query}`);
export const getFollowing = () => api.get('/api/users/following');
export const toggleBlock = (username) => api.post(`/api/users/${username}/block`);
export const getBlockStatus = (username) => api.get(`/api/users/${username}/block-status`);
export const getBlockedUsers = () => api.get('/api/users/blocked');
export const getFollowers = (username) => api.get(`/api/users/${username}/followers`);
export const getFollowingList = (username) => api.get(`/api/users/${username}/following-list`);
export const changePassword = (data) => api.post('/api/users/me/change-password', data);
export const verifyPassword = (currentPassword) => api.post('/api/users/me/verify-password', { currentPassword });